### ISSUE TITLE
Test not passing until you have installed and running mongod service.

### ISSUE THREAD

**Issue by venikman** [supercharge/framework#39]
I was not able to pass tests from fresh copied master branch (after run `npm install`) untill I install `mongod` and start service.
I have never used MongoDB before so I haven't mongo installed.

I didn't find any docs or steps about it. But I was able to figured out, my steps: 
1. Install `mongod` via brew, 
```sh
  brew tap mongodb/brew
  brew install mongodb-community@4.2
```
2. Start service on background: 
```sh
  brew services start mongodb-community@4.2
```

I think it would be nice to have some contribution guide or FAQ sections with problems. 
What do you have in mind @marcuspoehls ?

**Comment by marcuspoehls** [comment]
@venikman Good catch! You're right, testing the Supercharge framework requires an available MongoDB instance. At this point, this is the only requirement.

I like your idea for a contribution guide/FAQ. This should be part of the repo Readme. Looking some months ahead, it'll probably be required to also have a Redis server running.

Thank you for sharing your way to run MongoDB on macOS! I'll leave this issue open to keep me reminded adding the new contribution section to the readme.
